apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    kiamol: ch08-lab
spec:
  type: LoadBalancer
  ports:
    - port: 8088
      targetPort: 80
  selector:
    app: ch08-lab-web # pod에 설정한 값을 지정
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-stateful
  labels:
    kiamol: ch08-lab
spec:
  selector:
    matchLabels:
      app: ch08-lab-web
  serviceName: ch08-lab-web # TODO: 이거 뭐하는 놈인지 알아봐야함
  replicas: 3
  template:
    metadata:
      labels:
        app: ch08-lab-web
    spec:
      containers:
        - image: nginx:1.17-alpine
          name: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: logs
              mountPath: /var/log/nginx/
      volumes:
        - name: logs
          emptyDir: {}
